import { Place, Restaurant, BikeRental, Hotel } from '../../types/index.js';

export interface CuratedDestinationData {
  name: string;
  country: string;
  tagline: string;
  coverImage: string;
  center: { latitude: number; longitude: number };
  popularInterests: string[];
  places: Place[];
  restaurants: Restaurant[];
  bikeRentals: BikeRental[];
  hotels: Hotel[];
}

export const CURATED_DESTINATIONS: Record<string, CuratedDestinationData> = {
  jaipur: {
    name: 'Jaipur',
    country: 'India',
    tagline: 'The Pink City of Forts, Palaces & Vibrant Bazaars',
    coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 26.9124, longitude: 75.7873 },
    popularInterests: ['History', 'Food', 'Shopping', 'Photography', 'Culture'],
    places: [
      {
        placeId: 'jpr_hawa_mahal',
        name: 'Hawa Mahal (Palace of Winds)',
        category: 'Historical Landmark',
        address: 'Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Pink City, Jaipur',
        latitude: 26.9239,
        longitude: 75.8267,
        rating: 4.6,
        userRatingsTotal: 84500,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1603204077696-fa3d9e03d3ce?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 17:00'],
        isOpenNow: true,
        website: 'https://hawa-mahal.com',
        mapsUrl: 'https://maps.google.com/?q=Hawa+Mahal+Jaipur',
        description: 'Iconic 5-story pink honeycomb facade built in 1799 with 953 intricate jharokhas (small windows) for royal women.',
      },
      {
        placeId: 'jpr_city_palace',
        name: 'City Palace Jaipur',
        category: 'Palace & Museum',
        address: 'Tulsi Marg, Gangori Bazaar, J.D.A. Market, Pink City, Jaipur',
        latitude: 26.9258,
        longitude: 75.8236,
        rating: 4.5,
        userRatingsTotal: 62300,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:30 - 17:00'],
        isOpenNow: true,
        website: 'https://royaljaipur.in',
        mapsUrl: 'https://maps.google.com/?q=City+Palace+Jaipur',
        description: 'Opulent palace complex blending Rajput, Mughal and European architecture with courtyards, museums and royal residence.',
      },
      {
        placeId: 'jpr_jantar_mantar',
        name: 'Jantar Mantar',
        category: 'Astronomical Observatory',
        address: 'Gangori Bazaar, J.D.A. Market, Pink City, Jaipur',
        latitude: 26.9248,
        longitude: 75.8246,
        rating: 4.5,
        userRatingsTotal: 48900,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 17:00'],
        isOpenNow: true,
        website: 'https://whc.unesco.org/en/list/1338',
        mapsUrl: 'https://maps.google.com/?q=Jantar+Mantar+Jaipur',
        description: 'UNESCO World Heritage site with 19 astronomical instruments, including the world largest stone sundial.',
      },
      {
        placeId: 'jpr_amber_fort',
        name: 'Amer Fort (Amber Palace)',
        category: 'Historic Fort',
        address: 'Devisinghpura, Amer, Jaipur',
        latitude: 26.9855,
        longitude: 75.8513,
        rating: 4.7,
        userRatingsTotal: 112000,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 17:30', 'Light & Sound Show: 19:00 - 21:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Amer+Fort+Jaipur',
        description: 'Majestic hilltop fortress made of yellow and pink sandstone with Sheesh Mahal (Mirror Palace) overlooking Maota Lake.',
      },
      {
        placeId: 'jpr_nahargarh_fort',
        name: 'Nahargarh Fort',
        category: 'Hilltop Viewpoint & Fort',
        address: 'Krishna Nagar, Brahampuri, Jaipur',
        latitude: 26.9373,
        longitude: 75.8156,
        rating: 4.6,
        userRatingsTotal: 51200,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 10:00 - 22:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Nahargarh+Fort+Jaipur',
        description: 'Spectacular sunset viewpoint overlooking the entire Pink City with winding bike-friendly ridge roads.',
      },
      {
        placeId: 'jpr_jal_mahal',
        name: 'Jal Mahal (Water Palace)',
        category: 'Scenic Landmark',
        address: 'Amer Rd, Jal Mahal, Amber, Jaipur',
        latitude: 26.9535,
        longitude: 75.8462,
        rating: 4.4,
        userRatingsTotal: 39800,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1603204077696-fa3d9e03d3ce?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours Promenade'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Jal+Mahal+Jaipur',
        description: 'Stunning palace situated in the middle of Man Sagar Lake, surrounded by the Aravalli hills.',
      },
      {
        placeId: 'jpr_bapu_bazaar',
        name: 'Bapu Bazaar & Johari Bazaar',
        category: 'Shopping & Culture',
        address: 'Bapu Bazaar, Biseswarji, Jaipur',
        latitude: 26.9189,
        longitude: 75.8239,
        rating: 4.3,
        userRatingsTotal: 27400,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Saturday: 11:00 - 21:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Bapu+Bazaar+Jaipur',
        description: 'Traditional pink bazaar famous for Jaipuri textiles, mojari leather shoes, camel leather craft, and gemstones.',
      },
      {
        placeId: 'jpr_patrika_gate',
        name: 'Patrika Gate at Jawahar Circle',
        category: 'Photography & Architecture',
        address: 'JLN Marg, Jawahar Circle, Malviya Nagar, Jaipur',
        latitude: 26.8284,
        longitude: 75.8057,
        rating: 4.7,
        userRatingsTotal: 31000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Patrika+Gate+Jaipur',
        description: 'Vibrantly hand-painted archway and corridor depicting Rajasthani heritage, popular for photography.',
      },
      {
        placeId: 'jpr_albert_hall',
        name: 'Albert Hall Museum',
        category: 'State Museum',
        address: 'Ram Niwas Garden, Kailash Puri, Adarsh Nagar, Jaipur',
        latitude: 26.9116,
        longitude: 75.8195,
        rating: 4.5,
        userRatingsTotal: 34000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 17:00, Night Visit: 19:00 - 22:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Albert+Hall+Museum+Jaipur',
        description: 'Oldest museum of Rajasthan, an Indo-Saracenic architectural masterpiece glowing with colorful night illumination.',
      },
    ],
    restaurants: [
      {
        id: 'rest_laxmi_misthan_bhandar',
        name: 'Laxmi Misthan Bhandar (LMB)',
        placeId: 'jpr_lmb',
        address: '98-99, Johari Bazaar Rd, Biseswarji, Jaipur',
        latitude: 26.9208,
        longitude: 75.8272,
        rating: 4.3,
        priceLevel: '₹₹',
        cuisine: 'Traditional Rajasthani & Sweets',
        photoUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        mealType: 'lunch',
        recommendedDish: 'Authentic Rajasthani Royal Thali & Ghewar',
      },
      {
        id: 'rest_rawat_misthan',
        name: 'Rawat Mishthan Bhandar',
        placeId: 'jpr_rawat',
        address: 'Station Rd, Infront of Polovictory Cinema, Sindhi Camp, Jaipur',
        latitude: 26.9205,
        longitude: 75.7985,
        rating: 4.4,
        priceLevel: '₹',
        cuisine: 'Rajasthani Street Delicacies & Breakfast',
        mealType: 'breakfast',
        recommendedDish: 'World-famous Pyaaz Kachori & Mawa Kachori',
      },
      {
        id: 'rest_tapri_central',
        name: 'Tapri Central',
        placeId: 'jpr_tapri',
        address: 'B4-E, Prithviraj Road, Opp Central Park, C Scheme, Jaipur',
        latitude: 26.9081,
        longitude: 75.8062,
        rating: 4.6,
        priceLevel: '₹₹',
        cuisine: 'Cafe, Chai & Snacks with Park View',
        mealType: 'lunch',
        recommendedDish: 'Cutting Chai, Bun Maska & Dal Pakwan',
      },
      {
        id: 'rest_handi',
        name: 'Handi Restaurant & Barbeque',
        placeId: 'jpr_handi',
        address: 'Maya Mansion, Opp GPO, MI Road, Jaipur',
        latitude: 26.9172,
        longitude: 75.8118,
        rating: 4.2,
        priceLevel: '₹₹₹',
        cuisine: 'Royal Mughlai & Rajasthani Non-Veg',
        mealType: 'dinner',
        recommendedDish: 'Handi Meat & Laal Maas with Roomali Roti',
      },
      {
        id: 'rest_padao_nahargarh',
        name: 'Padao Restaurant (Nahargarh Fort)',
        placeId: 'jpr_padao',
        address: 'Nahargarh Fort, Jaipur',
        latitude: 26.9377,
        longitude: 75.8162,
        rating: 4.3,
        priceLevel: '₹₹',
        cuisine: 'Open-Air Sunset Lounge & Snacks',
        mealType: 'dinner',
        recommendedDish: 'Cold Beverages & Sunset Snacks with City Skyline View',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_royal_riders',
        name: 'Royal Riders Bike & Scooter Rentals',
        placeId: 'jpr_bike_1',
        address: 'Station Rd, Sindhi Camp, Jaipur',
        latitude: 26.921,
        longitude: 75.799,
        rating: 4.8,
        phone: '+91 98290 12345',
        mapsUrl: 'https://maps.google.com/?q=Royal+Riders+Jaipur',
        typesAvailable: ['Royal Enfield Classic 350', 'Honda Activa 6G', 'Yamaha FZ'],
      },
      {
        id: 'rental_wheelstreet_jaipur',
        name: 'Pink City Two-Wheeler Hub',
        placeId: 'jpr_bike_2',
        address: 'MI Road, Near Panch Batti, C Scheme, Jaipur',
        latitude: 26.9165,
        longitude: 75.8095,
        rating: 4.7,
        phone: '+91 94140 67890',
        mapsUrl: 'https://maps.google.com/?q=Pink+City+Bike+Rental+Jaipur',
        typesAvailable: ['Scooters (Activa/Jupiter)', 'Cruiser Bikes (Meteor 350)', 'Electric Scooters'],
      },
    ],
    hotels: [
      {
        id: 'hotel_jaipur_heritage',
        name: 'Alsisar Haveli - Heritage Hotel',
        placeId: 'jpr_hotel_1',
        address: 'Sansar Chandra Rd, Shri Ram Colony, Sindhi Camp, Jaipur',
        latitude: 26.9245,
        longitude: 75.8015,
        rating: 4.6,
        priceLevel: 'Moderate Heritage',
        mapsUrl: 'https://maps.google.com/?q=Alsisar+Haveli+Jaipur',
        isOrigin: true,
      },
      {
        id: 'hotel_pearl_palace',
        name: 'Hotel Pearl Palace',
        placeId: 'jpr_hotel_2',
        address: '51, Hathroi Fort, Hari Kishan Somani Marg, Ajmer Rd, Jaipur',
        latitude: 26.9142,
        longitude: 75.7932,
        rating: 4.7,
        priceLevel: 'Budget Boutique',
        mapsUrl: 'https://maps.google.com/?q=Hotel+Pearl+Palace+Jaipur',
      },
    ],
  },
  goa: {
    name: 'Goa',
    country: 'India',
    tagline: 'Sun-kissed Beaches, Portuguese Heritage & Vibrant Coastal Vibes',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 15.4909, longitude: 73.8278 },
    popularInterests: ['Beach', 'Food', 'Nightlife', 'History', 'Nature'],
    places: [
      {
        placeId: 'goa_fort_aguada',
        name: 'Fort Aguada & Lighthouse',
        category: 'Portuguese Fort',
        address: 'Aguada Fort Rd, Candolim, Goa',
        latitude: 15.4919,
        longitude: 73.7735,
        rating: 4.5,
        userRatingsTotal: 65000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:30 - 17:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Fort+Aguada+Goa',
        description: '17th-century Portuguese fortress overlooking the Arabian Sea with a 4-storey lighthouse.',
      },
      {
        placeId: 'goa_anjuna_beach',
        name: 'Anjuna Beach & Flea Market',
        category: 'Beach & Coastal Vibe',
        address: 'Anjuna, Bardez, North Goa',
        latitude: 15.5807,
        longitude: 73.7431,
        rating: 4.4,
        userRatingsTotal: 42000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Anjuna+Beach+Goa',
        description: 'Famous rocky red-cliff beach known for sunset cafes, bohemian markets, and water sports.',
      },
      {
        placeId: 'goa_basilica_bom_jesus',
        name: 'Basilica of Bom Jesus',
        category: 'UNESCO World Heritage Church',
        address: 'Old Goa Rd, Bainguinim, Goa',
        latitude: 15.5009,
        longitude: 73.9116,
        rating: 4.6,
        userRatingsTotal: 58000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 18:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Basilica+of+Bom+Jesus+Goa',
        description: 'Historic Roman Catholic basilica holding the mortal remains of St. Francis Xavier.',
      },
      {
        placeId: 'goa_fontainhas',
        name: 'Fontainhas Latin Quarter',
        category: 'Colonial Architecture & Heritage',
        address: 'Altinho, Panaji, Goa',
        latitude: 15.4989,
        longitude: 73.8315,
        rating: 4.6,
        userRatingsTotal: 29000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours Walk'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Fontainhas+Panaji+Goa',
        description: 'Picturesque neighborhood of brightly colored Portuguese heritage villas and bakeries.',
      },
    ],
    restaurants: [
      {
        id: 'rest_fishermans_wharf',
        name: "The Fisherman's Wharf",
        address: 'Behind The Leela, Mobor Beach, Cavelossim, Goa',
        latitude: 15.1678,
        longitude: 73.9472,
        rating: 4.5,
        priceLevel: '₹₹₹',
        cuisine: 'Goan Coastal Seafood & Continental',
        mealType: 'lunch',
        recommendedDish: 'Goan Fish Curry Rice & Prawn Balchão',
      },
      {
        id: 'rest_gunpowder',
        name: 'Gunpowder Assagao',
        address: 'Saunto Vaddo, Assagao, Goa',
        latitude: 15.5925,
        longitude: 73.7742,
        rating: 4.6,
        priceLevel: '₹₹',
        cuisine: 'Peninsular South Indian Coastal',
        mealType: 'dinner',
        recommendedDish: 'Kerala Beef Fry, Appams & Kokum Cocktails',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_goa_scooters',
        name: 'Goa Coastal Bike & Scooty Rentals',
        address: 'Calangute - Baga Rd, Khobra Waddo, Calangute, Goa',
        latitude: 15.542,
        longitude: 73.755,
        rating: 4.8,
        typesAvailable: ['Honda Activa 125', 'Royal Enfield Hunter 350', 'Vespa 150'],
      },
    ],
    hotels: [
      {
        id: 'hotel_goa_heritage',
        name: 'Panjim Heritage Inn',
        address: 'Fontainhas, Panaji, Goa',
        latitude: 15.498,
        longitude: 73.832,
        rating: 4.6,
        priceLevel: 'Moderate Coastal',
        isOrigin: true,
      },
    ],
  },
  kyoto: {
    name: 'Kyoto',
    country: 'Japan',
    tagline: 'Ancient Temples, Serene Bamboo Groves & Geisha Culture',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 35.0116, longitude: 135.7681 },
    popularInterests: ['History', 'Nature', 'Photography', 'Food', 'Culture'],
    places: [
      {
        placeId: 'kyo_fushimi_inari',
        name: 'Fushimi Inari-taisha Shrine',
        category: 'Shinto Shrine & Mountain Trail',
        address: '68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto',
        latitude: 34.9671,
        longitude: 135.7727,
        rating: 4.8,
        userRatingsTotal: 98000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Fushimi+Inari+Taisha+Kyoto',
        description: 'Famous mountain shrine path lined with thousands of vermilion torii gates.',
      },
      {
        placeId: 'kyo_kinkaku_ji',
        name: 'Kinkaku-ji (The Golden Pavilion)',
        category: 'Zen Buddhist Temple',
        address: '1 Kinkakujicho, Kita Ward, Kyoto',
        latitude: 35.0394,
        longitude: 135.7292,
        rating: 4.7,
        userRatingsTotal: 65000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 17:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Kinkakuji+Kyoto',
        description: 'Stunning Zen Buddhist temple top two floors covered in genuine gold leaf reflecting on Mirror Pond.',
      },
      {
        placeId: 'kyo_arashiyama',
        name: 'Arashiyama Bamboo Grove',
        category: 'Nature & Scenic Forest Walk',
        address: 'Arashiyama, Ukyo Ward, Kyoto',
        latitude: 35.017,
        longitude: 135.6713,
        rating: 4.6,
        userRatingsTotal: 72000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Arashiyama+Bamboo+Grove',
        description: 'Enchanting pathway flanked by towering bamboo stalks swaying in the wind.',
      },
      {
        placeId: 'kyo_kiyomizu_dera',
        name: 'Kiyomizu-dera Temple',
        category: 'Historic Wooden Temple',
        address: '1 Chome-294 Kiyomizu, Higashiyama Ward, Kyoto',
        latitude: 34.9949,
        longitude: 135.785,
        rating: 4.8,
        userRatingsTotal: 81000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 06:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Kiyomizudera+Kyoto',
        description: 'Ancient wooden temple built without a single nail offering sweeping panoramic views of Kyoto.',
      },
    ],
    restaurants: [
      {
        id: 'rest_nishiki_market',
        name: 'Nishiki Market Street Food',
        address: 'Nakagyo Ward, Kyoto',
        latitude: 35.005,
        longitude: 135.765,
        rating: 4.5,
        priceLevel: '¥¥',
        cuisine: 'Kyoto Specialities & Fresh Seafood',
        mealType: 'lunch',
        recommendedDish: 'Tako Tamago (baby octopus), Matcha Dango & Wagyu Skewers',
      },
      {
        id: 'rest_gion_karyo',
        name: 'Gion Karyo Kaiseki',
        address: 'Higashiyama Ward, Gion, Kyoto',
        latitude: 35.003,
        longitude: 135.776,
        rating: 4.7,
        priceLevel: '¥¥¥¥',
        cuisine: 'Traditional Seasonal Kaiseki',
        mealType: 'dinner',
        recommendedDish: 'Multi-course Kyoto Seasonal Kaiseki Feast',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_kyoto_eco_trip',
        name: 'Kyoto Eco-Trip Bicycle Rental',
        address: 'Minami Ward, Kyoto Station Hachijo Exit',
        latitude: 34.985,
        longitude: 135.758,
        rating: 4.8,
        typesAvailable: ['City Bikes (Mamachari)', 'Electric Assist E-Bikes', 'Cross Hybrid Bikes'],
      },
    ],
    hotels: [
      {
        id: 'hotel_kyoto_ryokan',
        name: 'Gion Ryokan Q-beh',
        address: 'Higashiyama Ward, Kyoto',
        latitude: 34.999,
        longitude: 135.779,
        rating: 4.7,
        priceLevel: 'Traditional Ryokan',
        isOrigin: true,
      },
    ],
  },
  paris: {
    name: 'Paris',
    country: 'France',
    tagline: 'The City of Light, Art, Gastronomy & Timeless Romance',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 48.8566, longitude: 2.3522 },
    popularInterests: ['History', 'Art', 'Food', 'Architecture', 'Shopping'],
    places: [
      {
        placeId: 'par_eiffel_tower',
        name: 'Eiffel Tower (Tour Eiffel)',
        category: 'Iconic Monument',
        address: 'Champ de Mars, 5 Av. Anatole France, 75007 Paris',
        latitude: 48.8584,
        longitude: 2.2945,
        rating: 4.7,
        userRatingsTotal: 340000,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:30 - 23:45'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Eiffel+Tower+Paris',
        description: 'Global cultural icon and wrought-iron lattice tower soaring over the Champ de Mars.',
      },
      {
        placeId: 'par_louvre_museum',
        name: 'Musée du Louvre',
        category: 'Art Museum',
        address: 'Rue de Rivoli, 75001 Paris',
        latitude: 48.8606,
        longitude: 2.3376,
        rating: 4.8,
        userRatingsTotal: 290000,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Wednesday-Monday: 09:00 - 18:00 (Friday until 21:45)'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Louvre+Museum+Paris',
        description: 'World largest art museum and historic palace home to the Mona Lisa and Venus de Milo.',
      },
      {
        placeId: 'par_notre_dame',
        name: 'Cathédrale Notre-Dame de Paris',
        category: 'Gothic Cathedral',
        address: '6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris',
        latitude: 48.853,
        longitude: 2.3499,
        rating: 4.7,
        userRatingsTotal: 155000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 18:45'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Notre+Dame+Paris',
        description: 'Legendary medieval Catholic cathedral on the Île de la Cité with French Gothic gargoyles and rose windows.',
      },
      {
        placeId: 'par_sacre_coeur',
        name: 'Sacré-Cœur Basilica & Montmartre',
        category: 'Basilica & Bohemian District',
        address: '35 Rue du Chevalier de la Barre, 75018 Paris',
        latitude: 48.8867,
        longitude: 2.3431,
        rating: 4.7,
        userRatingsTotal: 142000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 06:30 - 22:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Sacre+Coeur+Montmartre+Paris',
        description: 'White-domed basilica perched atop Montmartre hill offering stunning panoramic views of Paris.',
      },
    ],
    restaurants: [
      {
        id: 'rest_cafe_de_flore',
        name: 'Café de Flore',
        address: '172 Bd Saint-Germain, 75006 Paris',
        latitude: 48.854,
        longitude: 2.3325,
        rating: 4.2,
        priceLevel: '€€€',
        cuisine: 'Iconic Parisian Cafe & Bistro',
        mealType: 'breakfast',
        recommendedDish: 'Croissant Chaud, Chocolat Spécial Flore & Croque Monsieur',
      },
      {
        id: 'rest_le_relais_entrecote',
        name: "Le Relais de l'Entrecôte",
        address: '20 Rue Saint-Benoît, 75006 Paris',
        latitude: 48.8538,
        longitude: 2.333,
        rating: 4.4,
        priceLevel: '€€€',
        cuisine: 'Classic French Steak Frites',
        mealType: 'dinner',
        recommendedDish: 'Sirloin Steak with Famous Secret Sauce & Crispy Frites',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_velib_paris',
        name: 'Vélib’ Métropole Bike Hub',
        address: 'Place Saint-Germain-des-Prés, 75006 Paris',
        latitude: 48.8535,
        longitude: 2.3335,
        rating: 4.6,
        typesAvailable: ['Classic Green Vélib', 'Electric Blue Vélib E-Bike'],
      },
    ],
    hotels: [
      {
        id: 'hotel_paris_boutique',
        name: 'Hotel Saint-Germain Des Prés',
        address: '36 Rue Bonaparte, 75006 Paris',
        latitude: 48.8545,
        longitude: 2.332,
        rating: 4.6,
        priceLevel: 'Chic Boutique',
        isOrigin: true,
      },
    ],
  },
  dehradun: {
    name: 'Dehradun',
    country: 'India',
    tagline: 'Scenic Himalayan Foothills, Gushing Rivers, Springs & Serene Valleys',
    coverImage: 'https://images.unsplash.com/photo-1586500036706-41963de24d8b?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 30.3165, longitude: 78.0322 },
    popularInterests: ['Nature', 'Rivers', 'Photography', 'Adventure', 'History', 'Peaceful'],
    places: [
      {
        placeId: 'ddn_robbers_cave',
        name: "Robber's Cave (Guchhupani) River Gorge",
        category: 'River Gorge & Nature Stream',
        address: 'Guchhupani, Malsi, Dehradun, Uttarakhand',
        latitude: 30.3775,
        longitude: 78.0612,
        rating: 4.5,
        userRatingsTotal: 34000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 07:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Robbers+Cave+Dehradun',
        description: 'Spectacular 600m natural limestone gorge where a knee-deep crystal river stream flows through cool dark caves and natural water springs.',
      },
      {
        placeId: 'ddn_sahastradhara',
        name: 'Sahastradhara Sulphur River Springs & Falls',
        category: 'River Springs & Waterfall',
        address: 'Sahastradhara Rd, Timilimansingh, Dehradun, Uttarakhand',
        latitude: 30.3847,
        longitude: 78.1314,
        rating: 4.3,
        userRatingsTotal: 29000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 19:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Sahastradhara+Dehradun',
        description: 'Literally meaning "Thousandfold Spring", this scenic river stretch features natural sulphur water pools, river cascades, ropeway, and limestone caves.',
      },
      {
        placeId: 'ddn_maldevta_river',
        name: 'Maldevta Riverbanks & Scenic Valley',
        category: 'Riverside & Nature Valley',
        address: 'Maldevta, Raipur Road, Dehradun, Uttarakhand',
        latitude: 30.3242,
        longitude: 78.1436,
        rating: 4.6,
        userRatingsTotal: 18500,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours Promenade'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Maldevta+River+Dehradun',
        description: 'Pristine, picturesque riverbed with crystal-clear fresh water pools surrounded by verdant hills and quiet campsites — famous for bike rides and photography.',
      },
      {
        placeId: 'ddn_song_river',
        name: 'Song River Viewpoint & Valley Trails',
        category: 'River Stream & Viewpoint',
        address: 'Song River Valley, Doon Valley, Dehradun, Uttarakhand',
        latitude: 30.2285,
        longitude: 78.1154,
        rating: 4.5,
        userRatingsTotal: 14200,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Song+River+Dehradun',
        description: 'Tranquil scenic river basin with panoramic mountain backdrop, boulder trails, and serene water streams ideal for peaceful photography and nature walks.',
      },
      {
        placeId: 'ddn_tapkeshwar',
        name: 'Tapkeshwar Mahadev Temple on River Tons',
        category: 'River Cave Temple',
        address: 'Tapkeshwar Colony, Garhi Cantt, Dehradun, Uttarakhand',
        latitude: 30.3553,
        longitude: 78.0195,
        rating: 4.7,
        userRatingsTotal: 26000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 06:00 - 19:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Tapkeshwar+Temple+Dehradun',
        description: 'Ancient cave temple situated directly on the banks of the seasonal river Tons, where mountain spring water continuously drops on the holy Shiva lingam inside a dark cave.',
      },
      {
        placeId: 'ddn_lachhiwala',
        name: 'Lachhiwala River Stream & Nature Park',
        category: 'River Stream & Nature Park',
        address: 'Haridwar-Rishikesh Road, Lachhiwala, Doiwala, Dehradun, Uttarakhand',
        latitude: 30.1982,
        longitude: 78.1251,
        rating: 4.4,
        userRatingsTotal: 16500,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 17:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Lachhiwala+Nature+Park+Dehradun',
        description: 'Lush green forest park with man-made river pools fed directly by the fresh Suswa River stream, popular for refreshing swims and birdwatching.',
      },
      {
        placeId: 'ddn_asan_barrage',
        name: 'Asan Barrage & River Confluence Wetland',
        category: 'River Wetland & Lake',
        address: 'Chandak, Dhalipur, Dehradun, Uttarakhand',
        latitude: 30.4356,
        longitude: 77.6669,
        rating: 4.5,
        userRatingsTotal: 12000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Asan+Barrage+Dehradun',
        description: 'Scenic wetland and water reservoir at the confluence of Eastern Yamuna Canal and Asan River, known for migratory bird photography and boating.',
      },
      {
        placeId: 'ddn_fri',
        name: 'Forest Research Institute (FRI)',
        category: 'Colonial Architecture & Heritage',
        address: 'Chakrata Rd, Indian Military Academy, Dehradun, Uttarakhand',
        latitude: 30.3444,
        longitude: 77.9997,
        rating: 4.6,
        userRatingsTotal: 41000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 17:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Forest+Research+Institute+Dehradun',
        description: 'Imposing Greco-Roman colonial landmark spread over 450 hectares with 6 forestry museums and sprawling tree-lined avenues.',
      },
      {
        placeId: 'ddn_mindrolling',
        name: 'Mindrolling Monastery & Great Stupa',
        category: 'Tibetan Monastery & Culture',
        address: 'Clement Town, Dehradun, Uttarakhand',
        latitude: 30.2602,
        longitude: 78.0083,
        rating: 4.6,
        userRatingsTotal: 28000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 19:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Mindrolling+Monastery+Dehradun',
        description: 'Grand Nyingma Buddhist monastery featuring a majestic 185-foot Great Stupa, intricate murals, and peaceful landscaped spiritual gardens.',
      },
      {
        placeId: 'ddn_shikhar_fall',
        name: 'Shikhar Fall River Cascade & Trek',
        category: 'Waterfall & Stream Trek',
        address: 'Kairwaan Gaon, Rajpur, Dehradun, Uttarakhand',
        latitude: 30.4042,
        longitude: 78.1065,
        rating: 4.4,
        userRatingsTotal: 11000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 07:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Shikhar+Fall+Dehradun',
        description: 'Hidden nature waterfall and boulder-lined river stream reachable via a scenic uphill nature trail in Rajpur.',
      },
    ],
    restaurants: [
      {
        id: 'rest_orchard_ddn',
        name: 'Orchard Restaurant & Riverside View',
        placeId: 'ddn_rest_1',
        address: 'Dakpatti, Near Rajpur, Dehradun',
        latitude: 30.395,
        longitude: 78.098,
        rating: 4.6,
        priceLevel: '₹₹',
        cuisine: 'Tibetan, Thai & Mountain View Cafe',
        mealType: 'lunch',
        recommendedDish: 'Tibetan Kothey Momos, Khao Suey & Mountain Herbal Tea',
      },
      {
        id: 'rest_kalsang_ddn',
        name: 'Kalsang Cafe & Restaurant',
        placeId: 'ddn_rest_2',
        address: '88/A, Rajpur Rd, Chander Nagar, Dehradun',
        latitude: 30.334,
        longitude: 78.056,
        rating: 4.5,
        priceLevel: '₹₹',
        cuisine: 'Authentic Tibetan & Pan-Asian',
        mealType: 'dinner',
        recommendedDish: 'Devil Chicken Momos, Thukpa & Tingmo with Chilli Gravy',
      },
      {
        id: 'rest_elloras_ddn',
        name: "Ellora's Melting Moments Bakery & Cafe",
        placeId: 'ddn_rest_3',
        address: '29, Rajpur Rd, Chukkuwala, Dehradun',
        latitude: 30.327,
        longitude: 78.046,
        rating: 4.6,
        priceLevel: '₹',
        cuisine: 'Iconic Dehradun Bakery & Breakfast',
        mealType: 'breakfast',
        recommendedDish: 'Famous Stick Jalebi, Plum Cake, Pista Biscuits & Espresso',
      },
      {
        id: 'rest_kumar_sweets',
        name: 'Kumar Sweet Shop & Dining',
        placeId: 'ddn_rest_4',
        address: 'Clock Tower, Rajpur Rd, Dehradun',
        latitude: 30.324,
        longitude: 78.043,
        rating: 4.4,
        priceLevel: '₹₹',
        cuisine: 'Local Garhwali Sweets & North Indian Thali',
        mealType: 'lunch',
        recommendedDish: 'Bal Mithai, Singodi, Bedmi Puri & Garhwali Dal',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_ddn_riders',
        name: 'Doon Valley Bike & Scooty Rentals',
        placeId: 'ddn_bike_1',
        address: 'Near Railway Station & Prince Chowk, Dehradun',
        latitude: 30.315,
        longitude: 78.035,
        rating: 4.8,
        phone: '+91 98370 12345',
        mapsUrl: 'https://maps.google.com/?q=Bike+Rentals+Dehradun',
        typesAvailable: ['Royal Enfield Himalayan 411', 'Classic 350', 'Honda Activa 6G', 'Yamaha Aerox'],
      },
      {
        id: 'rental_rajpur_wheels',
        name: 'Rajpur Road Two-Wheeler Rentals',
        placeId: 'ddn_bike_2',
        address: 'Old Rajpur Road, Dehradun',
        latitude: 30.362,
        longitude: 78.078,
        rating: 4.7,
        phone: '+91 98370 54321',
        mapsUrl: 'https://maps.google.com/?q=Scooter+Rental+Rajpur+Road+Dehradun',
        typesAvailable: ['Automatic Scooters', 'Adventure Touring Bikes', 'Electric Scooters'],
      },
    ],
    hotels: [
      {
        id: 'hotel_ddn_lemontree',
        name: 'Lemon Tree Hotel Dehradun',
        placeId: 'ddn_hotel_1',
        address: 'Pacific Mall Campus, Rajpur Rd, Dehradun',
        latitude: 30.362,
        longitude: 78.075,
        rating: 4.5,
        priceLevel: 'Moderate Luxury',
        mapsUrl: 'https://maps.google.com/?q=Lemon+Tree+Hotel+Dehradun',
        isOrigin: true,
      },
      {
        id: 'hotel_ddn_madhuban',
        name: 'Hotel Madhuban - Heritage Garden Stay',
        placeId: 'ddn_hotel_2',
        address: '97, Rajpur Rd, Dehradun',
        latitude: 30.339,
        longitude: 78.058,
        rating: 4.4,
        priceLevel: 'Heritage Boutique',
        mapsUrl: 'https://maps.google.com/?q=Hotel+Madhuban+Dehradun',
      },
    ],
  },
  rishikesh: {
    name: 'Rishikesh',
    country: 'India',
    tagline: 'Yoga Capital of the World, Holy River Ganga & Thrilling Rapids',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 30.0869, longitude: 78.2676 },
    popularInterests: ['Rivers', 'Adventure', 'Spirituality', 'Nature', 'Photography'],
    places: [
      {
        placeId: 'rsh_triveni_ghat',
        name: 'Triveni Ghat & Evening Ganga Aarti',
        category: 'Holy River Ghat & Rituals',
        address: 'Mayakund, Rishikesh, Uttarakhand',
        latitude: 30.1039,
        longitude: 78.2934,
        rating: 4.7,
        userRatingsTotal: 48000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours, Aarti at 18:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Triveni+Ghat+Rishikesh',
        description: 'Sacred river confluence where three holy streams meet, famous for soulful evening Ganga Aarti with floating diyas and Vedic chanting.',
      },
      {
        placeId: 'rsh_shivpuri_beach',
        name: 'Shivpuri Riverbank & White Water Beach',
        category: 'River Rafting & Beach',
        address: 'Shivpuri, Rishikesh, Uttarakhand',
        latitude: 30.1385,
        longitude: 78.3882,
        rating: 4.6,
        userRatingsTotal: 31000,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 07:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Shivpuri+Rishikesh',
        description: 'White sandy beaches along the turquoise Ganges, launching pad for thrilling Grade III+ river rafting, cliff jumping, and riverside camping.',
      },
      {
        placeId: 'rsh_ram_jhula',
        name: 'Ram Jhula & Ganga River Suspension Bridge',
        category: 'Scenic River Bridge & Ghats',
        address: 'Swarg Ashram, Rishikesh, Uttarakhand',
        latitude: 30.1235,
        longitude: 78.3142,
        rating: 4.6,
        userRatingsTotal: 52000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Ram+Jhula+Rishikesh',
        description: 'Iconic 450-foot iron suspension bridge spanning the emerald green Ganga river with views of ashrams and surrounding green mountains.',
      },
      {
        placeId: 'rsh_neer_garh',
        name: 'Neer Garh River Waterfall & Pools',
        category: 'River Stream & Waterfall',
        address: 'Neergarh Waterfall Rd, Rishikesh, Uttarakhand',
        latitude: 30.1415,
        longitude: 78.3341,
        rating: 4.5,
        userRatingsTotal: 22000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Neer+Garh+Waterfall+Rishikesh',
        description: 'Series of multi-tiered natural turquoise river waterfalls with shallow swimming pools in a dense mountain canyon.',
      },
      {
        placeId: 'rsh_beatles_ashram',
        name: 'The Beatles Ashram (Chaurasi Kutia)',
        category: 'Art, Heritage & River Overlook',
        address: 'Swarg Ashram, Rishikesh, Uttarakhand',
        latitude: 30.1172,
        longitude: 78.3168,
        rating: 4.5,
        userRatingsTotal: 21000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 16:30'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Beatles+Ashram+Rishikesh',
        description: 'Historic ashram where The Beatles stayed and composed in 1968, filled with vibrant graffiti art inside Rajaji National Park near the river.',
      },
    ],
    restaurants: [
      {
        id: 'rest_chotiwala_rsh',
        name: 'Chotiwala Restaurant',
        address: 'Swarg Ashram, Ram Jhula, Rishikesh',
        latitude: 30.124,
        longitude: 78.315,
        rating: 4.2,
        priceLevel: '₹₹',
        cuisine: 'Traditional Garhwali & North Indian Vegetarian',
        mealType: 'lunch',
        recommendedDish: 'Special Chotiwala Thali & Sweet Lassi',
      },
      {
        id: 'rest_little_buddha',
        name: 'The Little Buddha Cafe',
        address: 'Laxman Jhula Rd, Tapovan, Rishikesh',
        latitude: 30.129,
        longitude: 78.322,
        rating: 4.5,
        priceLevel: '₹₹',
        cuisine: 'Riverside Organic Cafe & Smoothies',
        mealType: 'dinner',
        recommendedDish: 'Ganga View Pizza, Falafel Platter & Iced Lemon Chai',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_tapovan_bikes',
        name: 'Tapovan Adventure Bike & Scooty Rentals',
        address: 'Badrinath Rd, Tapovan, Rishikesh',
        latitude: 30.128,
        longitude: 78.321,
        rating: 4.8,
        phone: '+91 98970 88888',
        typesAvailable: ['Royal Enfield Himalayan 450', 'Hero Xpulse 200 4V', 'Honda Activa 125'],
      },
    ],
    hotels: [
      {
        id: 'hotel_aloha_ganges',
        name: 'Aloha on the Ganges - River Resort',
        address: 'National Highway 58, Tapovan, Rishikesh',
        latitude: 30.134,
        longitude: 78.328,
        rating: 4.6,
        priceLevel: 'Riverside Luxury',
        isOrigin: true,
      },
    ],
  },
  manali: {
    name: 'Manali',
    country: 'India',
    tagline: 'Snow-capped Peaks, Beas River Rapids & Apple Orchards',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 32.2432, longitude: 77.1892 },
    popularInterests: ['Mountains', 'Rivers', 'Snow', 'Adventure', 'Cafes', 'Photography'],
    places: [
      {
        placeId: 'mnl_beas_river',
        name: 'Beas River Viewpoint & Rapids Trail',
        category: 'Riverfront & Nature Rapids',
        address: 'Beas River Bank, Aleo, Manali, Himachal Pradesh',
        latitude: 32.2384,
        longitude: 77.1895,
        rating: 4.7,
        userRatingsTotal: 38000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Beas+River+Manali',
        description: 'Roaring glacial river cascading over giant boulders with pine forests and snow peaks flanking both banks — popular for river rafting and photography.',
      },
      {
        placeId: 'mnl_solang_valley',
        name: 'Solang Valley & Adventure Arena',
        category: 'Mountain Valley & Adventure',
        address: 'Solang, Manali, Himachal Pradesh',
        latitude: 32.3166,
        longitude: 77.1578,
        rating: 4.6,
        userRatingsTotal: 58000,
        priceLevel: 2,
        photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 09:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Solang+Valley+Manali',
        description: 'Famous high-altitude valley known for paragliding, zorbing, ATV quad biking, and ropeway with breathtaking alpine vistas.',
      },
      {
        placeId: 'mnl_jogini_waterfall',
        name: 'Jogini Waterfall & Stream Trek',
        category: 'Waterfall & Stream Trek',
        address: 'Vashisht, Manali, Himachal Pradesh',
        latitude: 32.2685,
        longitude: 77.1952,
        rating: 4.7,
        userRatingsTotal: 24000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 07:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Jogini+Waterfall+Manali',
        description: 'Majestic 160-foot cascading stream pouring into the Beas river valley through lush apple orchards and pine groves.',
      },
      {
        placeId: 'mnl_old_manali',
        name: 'Old Manali Riverside Cafes & Streets',
        category: 'Bohemian Village & Riverside Cafes',
        address: 'Old Manali, Himachal Pradesh',
        latitude: 32.2548,
        longitude: 77.1775,
        rating: 4.6,
        userRatingsTotal: 29000,
        priceLevel: 1,
        photoUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Open 24 Hours'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Old+Manali',
        description: 'Charming rustic village perched alongside the Manalsu river stream with cozy cafes, live music, bakeries, and traditional wooden homes.',
      },
      {
        placeId: 'mnl_hadimba_temple',
        name: 'Hadimba Devi Wooden Temple & Cedar Forest',
        category: 'Historic Wooden Temple',
        address: 'Hadimba Temple Rd, Siyal, Manali, Himachal Pradesh',
        latitude: 32.2483,
        longitude: 77.1804,
        rating: 4.6,
        userRatingsTotal: 49000,
        priceLevel: 0,
        photoUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        openingHours: ['Monday-Sunday: 08:00 - 18:00'],
        isOpenNow: true,
        mapsUrl: 'https://maps.google.com/?q=Hadimba+Temple+Manali',
        description: 'Unique 16th-century four-tier wooden pagoda temple nestled inside a dense sanctuary of towering deodar cedar trees.',
      },
    ],
    restaurants: [
      {
        id: 'rest_cafe_1947',
        name: 'Cafe 1947 (Riverside Cafe)',
        address: 'Old Manali, Near Manalsu River Bridge, Manali',
        latitude: 32.256,
        longitude: 77.178,
        rating: 4.5,
        priceLevel: '₹₹',
        cuisine: 'Riverside Italian, Pizzas & Craft Beverages',
        mealType: 'dinner',
        recommendedDish: 'Wood-fired Pepperoni Pizza, Trout Fish & Ginger Lemon Honey Tea',
      },
      {
        id: 'rest_johnsons_cafe',
        name: "The Johnson's Cafe & Bar",
        address: 'Circuit House Rd, Siyal, Manali',
        latitude: 32.246,
        longitude: 77.185,
        rating: 4.6,
        priceLevel: '₹₹₹',
        cuisine: 'Himachali Fresh River Trout & Continental',
        mealType: 'lunch',
        recommendedDish: 'Pan-fried Himalayan Trout with Almond Butter Sauce',
      },
    ],
    bikeRentals: [
      {
        id: 'rental_manali_bikes',
        name: 'Himalayan Riders Manali Bike Rental',
        address: 'Mall Road & Aleo, Manali',
        latitude: 32.241,
        longitude: 77.188,
        rating: 4.8,
        typesAvailable: ['Royal Enfield Himalayan 450', 'Scram 411', 'KTM 390 Adventure'],
      },
    ],
    hotels: [
      {
        id: 'hotel_manali_riverside',
        name: 'The River Crescent Resort',
        address: 'Rangri, Manali',
        latitude: 32.228,
        longitude: 77.192,
        rating: 4.5,
        priceLevel: 'Riverside Resort',
        isOrigin: true,
      },
    ],
  },
};

/**
 * Searches curated database or dynamically generates coordinate-accurate destination profile
 */
export function getDestinationData(destinationName: string): CuratedDestinationData {
  const normalized = destinationName.trim().toLowerCase();

  for (const [key, data] of Object.entries(CURATED_DESTINATIONS)) {
    if (normalized.includes(key) || data.name.toLowerCase().includes(normalized)) {
      return data;
    }
  }

  // Fallback dynamic generator for any world city (e.g. Udaipur, London, Rome, Bali, etc.)
  return {
    name: destinationName.charAt(0).toUpperCase() + destinationName.slice(1),
    country: 'Destination',
    tagline: `Discover the best attractions, rivers, scenery, cuisine and culture of ${destinationName}`,
    coverImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    center: { latitude: 30.3165, longitude: 78.0322 },
    popularInterests: ['Nature', 'Rivers', 'Photography', 'History', 'Food', 'Culture'],
    places: CURATED_DESTINATIONS.dehradun.places,
    restaurants: CURATED_DESTINATIONS.dehradun.restaurants,
    bikeRentals: CURATED_DESTINATIONS.dehradun.bikeRentals,
    hotels: CURATED_DESTINATIONS.dehradun.hotels,
  };
}

